// auto-generated by generate_cpu_data.ts
export const CALL: string[] = [
    "from:0100 to:0000 -> pc:0000 sp:1FFE ret:0102",
    "from:0100 to:1000 -> pc:1000 sp:1FFE ret:0102",
    "from:0100 to:2000 -> pc:2000 sp:1FFE ret:0102",
    "from:0100 to:3000 -> pc:3000 sp:1FFE ret:0102",
    "from:0100 to:4000 -> pc:4000 sp:1FFE ret:0102",
    "from:0100 to:5000 -> pc:5000 sp:1FFE ret:0102",
    "from:0100 to:6000 -> pc:6000 sp:1FFE ret:0102",
    "from:0100 to:7000 -> pc:7000 sp:1FFE ret:0102",
    "from:0100 to:8000 -> pc:8000 sp:1FFE ret:0102",
    "from:0100 to:9000 -> pc:9000 sp:1FFE ret:0102",
    "from:0100 to:A000 -> pc:A000 sp:1FFE ret:0102",
    "from:0100 to:B000 -> pc:B000 sp:1FFE ret:0102",
    "from:0100 to:C000 -> pc:C000 sp:1FFE ret:0102",
    "from:0100 to:D000 -> pc:D000 sp:1FFE ret:0102",
    "from:0100 to:E000 -> pc:E000 sp:1FFE ret:0102",
    "from:0100 to:F000 -> pc:F000 sp:1FFE ret:0102",
];
