// auto-generated by generate_cpu_data.ts
export const RET: string[] = [
    "ret_addr:0000 -> pc:0000 sp:2000",
    "ret_addr:1000 -> pc:1000 sp:2000",
    "ret_addr:2000 -> pc:2000 sp:2000",
    "ret_addr:3000 -> pc:3000 sp:2000",
    "ret_addr:4000 -> pc:4000 sp:2000",
    "ret_addr:5000 -> pc:5000 sp:2000",
    "ret_addr:6000 -> pc:6000 sp:2000",
    "ret_addr:7000 -> pc:7000 sp:2000",
    "ret_addr:8000 -> pc:8000 sp:2000",
    "ret_addr:9000 -> pc:9000 sp:2000",
    "ret_addr:A000 -> pc:A000 sp:2000",
    "ret_addr:B000 -> pc:B000 sp:2000",
    "ret_addr:C000 -> pc:C000 sp:2000",
    "ret_addr:D000 -> pc:D000 sp:2000",
    "ret_addr:E000 -> pc:E000 sp:2000",
    "ret_addr:F000 -> pc:F000 sp:2000",
];
