// Generates test data tables for i8080 ALU and single-operand instructions.
// Run: bun tests/generate_cpu_data.ts

import { I8080 } from "../src/lib/core/i8080.ts";
import { Memory } from "../src/lib/core/rk86_memory.js";
import { hex8, hex16 } from "../src/lib/core/hex.js";

async function writeData(name: string, varName: string, results: string[]) {
    await Bun.write(
        `tests/cpu/${name}_data.ts`,
        `// auto-generated by generate_cpu_data.ts\nexport const ${varName}: string[] = [\n${results.map((r) => `    "${r}",`).join("\n")}\n];\n`,
    );
    console.log(`${name}: ${results.length} entries`);
}

const io = {
    input: (_port: number): number => 0,
    output: (_port: number, _value: number): void => {},
    interrupt: (_iff: number): void => {},
};

function createCPU(): { cpu: I8080; memory: Memory } {
    const memory = new Memory(undefined);
    const cpu = new I8080({ memory, io });
    return { cpu, memory };
}

function flags(cpu: I8080): string {
    return cpu.store_flags().toString(2).padStart(8, "0");
}

// --- DAA ---
// Format: "cf:C hf:H a:XX -> a:YY flags:FFFFFFFF"

{
    const { cpu } = createCPU();
    const results: string[] = [];

    for (let cf = 0; cf < 2; cf++) {
        for (let hf = 0; hf < 2; hf++) {
            for (let a = 0; a < 256; a++) {
                cpu.cf = cf;
                cpu.hf = hf;
                cpu.set_a(a);
                cpu.execute(0x27); // DAA
                results.push(`cf:${cf} hf:${hf} a:${hex8(a)} -> a:${hex8(cpu.a())} flags:${flags(cpu)}`);
            }
        }
    }

    await writeData("daa", "DAA", results);
}

// --- CPI ---
// Format: "a:XX imm8:YY -> a:ZZ flags:FFFFFFFF"

{
    const { cpu, memory } = createCPU();
    const results: string[] = [];

    for (let a = 0; a < 256; a++) {
        for (let imm8 = 0; imm8 < 256; imm8++) {
            cpu.pc = 0;
            cpu.set_a(a);
            cpu.retrieve_flags(0x00);
            memory.write_raw(0, imm8);
            cpu.execute(0xfe); // CPI
            results.push(`a:${hex8(a)} imm8:${hex8(imm8)} -> a:${hex8(cpu.a())} flags:${flags(cpu)}`);
        }
    }

    await writeData("cpi", "CPI", results);
}

// --- ALU immediate: ADI, ACI, SUI, SBI, ANI, ORI, XRI ---
// Format: "a:XX imm8:YY -> a:ZZ flags:FFFFFFFF"
// For ACI/SBI, also includes carry: "cf:C a:XX imm8:YY -> a:ZZ flags:FFFFFFFF"

type AluImm = { name: string; opcode: number; hasCarry: boolean };

const aluImmOps: AluImm[] = [
    { name: "adi", opcode: 0xc6, hasCarry: false },
    { name: "aci", opcode: 0xce, hasCarry: true },
    { name: "sui", opcode: 0xd6, hasCarry: false },
    { name: "sbi", opcode: 0xde, hasCarry: true },
    { name: "ani", opcode: 0xe6, hasCarry: false },
    { name: "ori", opcode: 0xf6, hasCarry: false },
    { name: "xri", opcode: 0xee, hasCarry: false },
];

for (const op of aluImmOps) {
    const { cpu, memory } = createCPU();
    const results: string[] = [];

    const carries = op.hasCarry ? [0, 1] : [0];
    for (const cf of carries) {
        for (let a = 0; a < 256; a++) {
            for (let imm8 = 0; imm8 < 256; imm8++) {
                cpu.pc = 0;
                cpu.set_a(a);
                cpu.retrieve_flags(0x00);
                cpu.cf = cf;
                memory.write_raw(0, imm8);
                cpu.execute(op.opcode);

                const prefix = op.hasCarry ? `cf:${cf} ` : "";
                results.push(`${prefix}a:${hex8(a)} imm8:${hex8(imm8)} -> a:${hex8(cpu.a())} flags:${flags(cpu)}`);
            }
        }
    }

    await writeData(op.name, op.name.toUpperCase(), results);
}

// --- Rotate: RLC, RRC, RAL, RAR ---
// Format: "cf:C a:XX -> a:ZZ cf:C"

type RotateOp = { name: string; opcode: number };

const rotateOps: RotateOp[] = [
    { name: "rlc", opcode: 0x07 },
    { name: "rrc", opcode: 0x0f },
    { name: "ral", opcode: 0x17 },
    { name: "rar", opcode: 0x1f },
];

for (const op of rotateOps) {
    const { cpu } = createCPU();
    const results: string[] = [];

    for (let cf = 0; cf < 2; cf++) {
        for (let a = 0; a < 256; a++) {
            cpu.pc = 0;
            cpu.set_a(a);
            cpu.cf = cf;
            cpu.execute(op.opcode);
            results.push(`cf:${cf} a:${hex8(a)} -> a:${hex8(cpu.a())} cf:${cpu.cf}`);
        }
    }

    await writeData(op.name, op.name.toUpperCase(), results);
}

// --- INR/DCR ---
// Format: "r:XX flags:IIIIIIII -> r:ZZ flags:FFFFFFFF"
// INR/DCR don't affect carry, so we test with flags=0

type IncrOp = { name: string; opcode: number };

const incrOps: IncrOp[] = [
    { name: "inr", opcode: 0x04 }, // INR B
    { name: "dcr", opcode: 0x05 }, // DCR B
];

for (const op of incrOps) {
    const { cpu } = createCPU();
    const results: string[] = [];

    for (let v = 0; v < 256; v++) {
        cpu.pc = 0;
        cpu.set_b(v);
        cpu.retrieve_flags(0x00);
        cpu.execute(op.opcode);
        results.push(`r:${hex8(v)} -> r:${hex8(cpu.b())} flags:${flags(cpu)}`);
    }

    await writeData(op.name, op.name.toUpperCase(), results);
}

// --- CMA ---
// Format: "a:XX -> a:ZZ"

{
    const { cpu } = createCPU();
    const results: string[] = [];

    for (let a = 0; a < 256; a++) {
        cpu.pc = 0;
        cpu.set_a(a);
        cpu.execute(0x2f); // CMA
        results.push(`a:${hex8(a)} -> a:${hex8(cpu.a())}`);
    }

    await writeData("cma", "CMA", results);
}

// --- STC/CMC ---

{
    const { cpu } = createCPU();

    const stcResults: string[] = [];
    for (let cf = 0; cf < 2; cf++) {
        cpu.cf = cf;
        cpu.execute(0x37);
        stcResults.push(`cf:${cf} -> cf:${cpu.cf}`);
    }
    await writeData("stc", "STC", stcResults);

    const cmcResults: string[] = [];
    for (let cf = 0; cf < 2; cf++) {
        cpu.cf = cf;
        cpu.execute(0x3f);
        cmcResults.push(`cf:${cf} -> cf:${cpu.cf}`);
    }
    await writeData("cmc", "CMC", cmcResults);
}

// --- Register ALU ops: ADD/ADC/SUB/SBB/ANA/ORA/XRA/CMP with register B ---
// Format: "a:XX b:YY -> a:ZZ flags:FFFFFFFF" (CMP doesn't change A)
// ADC/SBB: "cf:C a:XX b:YY -> a:ZZ flags:FFFFFFFF"

type AluReg = { name: string; opcode: number; hasCarry: boolean };

const aluRegOps: AluReg[] = [
    { name: "add_b", opcode: 0x80, hasCarry: false },
    { name: "adc_b", opcode: 0x88, hasCarry: true },
    { name: "sub_b", opcode: 0x90, hasCarry: false },
    { name: "sbb_b", opcode: 0x98, hasCarry: true },
    { name: "ana_b", opcode: 0xa0, hasCarry: false },
    { name: "ora_b", opcode: 0xb0, hasCarry: false },
    { name: "xra_b", opcode: 0xa8, hasCarry: false },
    { name: "cmp_b", opcode: 0xb8, hasCarry: false },
];

for (const op of aluRegOps) {
    const { cpu } = createCPU();
    const results: string[] = [];

    const carries = op.hasCarry ? [0, 1] : [0];
    for (const cf of carries) {
        for (let a = 0; a < 256; a++) {
            for (let b = 0; b < 256; b++) {
                cpu.pc = 0;
                cpu.set_a(a);
                cpu.set_b(b);
                cpu.retrieve_flags(0x00);
                cpu.cf = cf;
                cpu.execute(op.opcode);

                const prefix = op.hasCarry ? `cf:${cf} ` : "";
                results.push(`${prefix}a:${hex8(a)} b:${hex8(b)} -> a:${hex8(cpu.a())} flags:${flags(cpu)}`);
            }
        }
    }

    const varName = op.name.toUpperCase();
    await writeData(op.name, varName, results);
}

// --- DAD: 16-bit add to HL ---
// Format: "hl:XXXX rp:YYYY -> hl:ZZZZ cf:C"

type DadOp = { name: string; opcode: number; rpIndex: number };

const dadOps: DadOp[] = [
    { name: "dad_b", opcode: 0x09, rpIndex: 0 },
    { name: "dad_d", opcode: 0x19, rpIndex: 2 },
    { name: "dad_h", opcode: 0x29, rpIndex: 4 },
    { name: "dad_sp", opcode: 0x39, rpIndex: 6 },
];

for (const op of dadOps) {
    const { cpu } = createCPU();
    const results: string[] = [];

    // Test subset: 256 HL values × 256 RP values (stepping by 256)
    for (let hl = 0; hl < 0x10000; hl += 0x100) {
        for (let rp = 0; rp < 0x10000; rp += 0x100) {
            cpu.pc = 0;
            cpu.set_rp(4, hl);
            if (op.rpIndex === 4) {
                // DAD H: HL + HL, rp is same as HL
            } else if (op.rpIndex === 6) {
                cpu.sp = rp;
            } else {
                cpu.set_rp(op.rpIndex, rp);
            }
            cpu.cf = 0;
            cpu.execute(op.opcode);

            const rpVal = op.rpIndex === 4 ? hl : rp;
            results.push(`hl:${hex16(hl)} rp:${hex16(rpVal)} -> hl:${hex16(cpu.hl())} cf:${cpu.cf}`);
        }
    }

    const varName = op.name.toUpperCase();
    await writeData(op.name, varName, results);
}

// --- INX/DCX: 16-bit increment/decrement ---
// Format: "rp:XXXX -> rp:YYYY"

type InxOp = { name: string; opcode: number; rpIndex: number };

const inxOps: InxOp[] = [
    { name: "inx_b", opcode: 0x03, rpIndex: 0 },
    { name: "inx_d", opcode: 0x13, rpIndex: 2 },
    { name: "inx_h", opcode: 0x23, rpIndex: 4 },
    { name: "inx_sp", opcode: 0x33, rpIndex: 6 },
    { name: "dcx_b", opcode: 0x0b, rpIndex: 0 },
    { name: "dcx_d", opcode: 0x1b, rpIndex: 2 },
    { name: "dcx_h", opcode: 0x2b, rpIndex: 4 },
    { name: "dcx_sp", opcode: 0x3b, rpIndex: 6 },
];

for (const op of inxOps) {
    const { cpu } = createCPU();
    const results: string[] = [];

    // Test boundary values and sampling
    const testValues = [0x0000, 0x0001, 0x00ff, 0x0100, 0x7fff, 0x8000, 0xfffe, 0xffff];
    for (let v = 0; v < 0x10000; v += 0x100) testValues.push(v);
    const unique = [...new Set(testValues)].sort((a, b) => a - b);

    for (const v of unique) {
        cpu.pc = 0;
        if (op.rpIndex === 6) cpu.sp = v;
        else cpu.set_rp(op.rpIndex, v);
        cpu.execute(op.opcode);

        const result = op.rpIndex === 6 ? cpu.sp : cpu.rp(op.rpIndex);
        results.push(`rp:${hex16(v)} -> rp:${hex16(result)}`);
    }

    const varName = op.name.toUpperCase();
    await writeData(op.name, varName, results);
}

// --- PUSH/POP PSW round-trip ---
// Format: "a:XX flags:FFFFFFFF -> a:YY flags:GGGGGGGG"

{
    const { cpu, memory } = createCPU();
    const results: string[] = [];

    for (let a = 0; a < 256; a++) {
        for (let f = 0; f < 256; f += 4) { // sample flags
            cpu.pc = 0;
            cpu.sp = 0x2000;
            cpu.set_a(a);
            cpu.retrieve_flags(f);
            const origFlags = flags(cpu);

            cpu.execute(0xf5); // PUSH PSW

            // Corrupt A and flags
            cpu.set_a(0x00);
            cpu.retrieve_flags(0x00);

            cpu.execute(0xf1); // POP PSW

            results.push(`a:${hex8(a)} flags:${origFlags} -> a:${hex8(cpu.a())} flags:${flags(cpu)}`);
        }
    }

    await writeData("push_pop_psw", "PUSH_POP_PSW", results);
}

// --- MOV r,r: all 64 register-to-register moves (excluding M) ---
// Format: "mov R,R: src:XX -> dst:XX"

{
    const { cpu } = createCPU();
    const results: string[] = [];
    const regNames = ["B", "C", "D", "E", "H", "L", "M", "A"];

    for (let dst = 0; dst < 8; dst++) {
        if (dst === 6) continue; // skip M (memory)
        for (let src = 0; src < 8; src++) {
            if (src === 6) continue; // skip M
            for (let v = 0; v < 256; v += 17) { // sample values
                cpu.pc = 0;
                // Reset all regs
                for (let r = 0; r < 8; r++) if (r !== 6) cpu.set_reg(r, 0);
                cpu.set_reg(src, v);

                const opcode = 0x40 | (dst << 3) | src;
                cpu.execute(opcode);

                const dstVal = cpu.reg(dst);
                results.push(`mov ${regNames[dst]},${regNames[src]}: src:${hex8(v)} -> dst:${hex8(dstVal)}`);
            }
        }
    }

    await writeData("mov", "MOV", results);
}

// --- LXI: load 16-bit immediate ---
// Format: "rp -> rp:XXXX"

{
    const { cpu } = createCPU();
    const results: string[] = [];
    const ops = [
        { name: "lxi_b", opcode: 0x01, rpIndex: 0 },
        { name: "lxi_d", opcode: 0x11, rpIndex: 2 },
        { name: "lxi_h", opcode: 0x21, rpIndex: 4 },
        { name: "lxi_sp", opcode: 0x31, rpIndex: 6 },
    ];

    for (const op of ops) {
        const opResults: string[] = [];
        for (let v = 0; v < 0x10000; v += 0x100) {
            const { cpu, memory } = createCPU();
            cpu.pc = 0;
            memory.write_raw(0, v & 0xff);
            memory.write_raw(1, (v >> 8) & 0xff);
            cpu.execute(op.opcode);

            const result = op.rpIndex === 6 ? cpu.sp : cpu.rp(op.rpIndex);
            opResults.push(`imm16:${hex16(v)} -> rp:${hex16(result)}`);
        }
        await writeData(op.name, op.name.toUpperCase(), opResults);
    }
}

// --- MVI: move immediate to register ---
// Format: "imm8:XX -> r:YY"

{
    const regNames = ["B", "C", "D", "E", "H", "L", "M", "A"];
    const opcodes = [0x06, 0x0e, 0x16, 0x1e, 0x26, 0x2e, 0x36, 0x3e];

    for (let r = 0; r < 8; r++) {
        const { cpu, memory } = createCPU();
        const results: string[] = [];

        if (r === 6) {
            cpu.set_rp(4, 0x4000); // HL points to 0x4000 for M
        }

        for (let v = 0; v < 256; v++) {
            cpu.pc = 0;
            memory.write_raw(0, v);
            cpu.execute(opcodes[r]);

            const result = r === 6 ? memory.read_raw(0x4000) : cpu.reg(r);
            results.push(`imm8:${hex8(v)} -> r:${hex8(result)}`);
        }

        const name = `mvi_${regNames[r].toLowerCase()}`;
        await writeData(name, name.toUpperCase(), results);
    }
}

// --- LDAX/STAX ---
// Format: "addr:XXXX val:YY -> a:ZZ" / "a:XX -> addr:XXXX val:YY"

{
    const { cpu, memory } = createCPU();
    const ldaxResults: string[] = [];
    const staxResults: string[] = [];

    for (const rp of [0, 2]) { // BC, DE
        const rpName = rp === 0 ? "b" : "d";

        // LDAX
        const ldax: string[] = [];
        for (let v = 0; v < 256; v++) {
            cpu.pc = 0;
            cpu.set_rp(rp, 0x3000);
            memory.write_raw(0x3000, v);
            cpu.execute(rp === 0 ? 0x0a : 0x1a); // LDAX B / LDAX D
            ldax.push(`val:${hex8(v)} -> a:${hex8(cpu.a())}`);
        }
        await writeData(`ldax_${rpName}`, `LDAX_${rpName.toUpperCase()}`, ldax);

        // STAX
        const stax: string[] = [];
        for (let v = 0; v < 256; v++) {
            cpu.pc = 0;
            cpu.set_a(v);
            cpu.set_rp(rp, 0x3000);
            memory.write_raw(0x3000, 0);
            cpu.execute(rp === 0 ? 0x02 : 0x12); // STAX B / STAX D
            stax.push(`a:${hex8(v)} -> val:${hex8(memory.read_raw(0x3000))}`);
        }
        await writeData(`stax_${rpName}`, `STAX_${rpName.toUpperCase()}`, stax);
    }
}

// --- LDA/STA ---
// Format: "val:XX -> a:YY" / "a:XX -> val:YY"

{
    const { cpu, memory } = createCPU();

    const ldaResults: string[] = [];
    for (let v = 0; v < 256; v++) {
        cpu.pc = 0;
        memory.write_raw(0, 0x00); // addr low
        memory.write_raw(1, 0x30); // addr high = 0x3000
        memory.write_raw(0x3000, v);
        cpu.execute(0x3a); // LDA
        ldaResults.push(`val:${hex8(v)} -> a:${hex8(cpu.a())}`);
    }
    await writeData("lda", "LDA", ldaResults);

    const staResults: string[] = [];
    for (let v = 0; v < 256; v++) {
        cpu.pc = 0;
        memory.write_raw(0, 0x00);
        memory.write_raw(1, 0x30);
        cpu.set_a(v);
        memory.write_raw(0x3000, 0);
        cpu.execute(0x32); // STA
        staResults.push(`a:${hex8(v)} -> val:${hex8(memory.read_raw(0x3000))}`);
    }
    await writeData("sta", "STA", staResults);
}

// --- LHLD/SHLD ---

{
    const { cpu, memory } = createCPU();

    const lhldResults: string[] = [];
    for (let v = 0; v < 0x10000; v += 0x100) {
        cpu.pc = 0;
        memory.write_raw(0, 0x00);
        memory.write_raw(1, 0x30);
        memory.write_raw(0x3000, v & 0xff);
        memory.write_raw(0x3001, (v >> 8) & 0xff);
        cpu.execute(0x2a); // LHLD
        lhldResults.push(`val:${hex16(v)} -> hl:${hex16(cpu.hl())}`);
    }
    await writeData("lhld", "LHLD", lhldResults);

    const shldResults: string[] = [];
    for (let v = 0; v < 0x10000; v += 0x100) {
        cpu.pc = 0;
        memory.write_raw(0, 0x00);
        memory.write_raw(1, 0x30);
        cpu.set_rp(4, v);
        memory.write_raw(0x3000, 0);
        memory.write_raw(0x3001, 0);
        cpu.execute(0x22); // SHLD
        const lo = memory.read_raw(0x3000);
        const hi = memory.read_raw(0x3001);
        shldResults.push(`hl:${hex16(v)} -> val:${hex16((hi << 8) | lo)}`);
    }
    await writeData("shld", "SHLD", shldResults);
}

// --- PUSH/POP B, D, H ---

{
    for (const [rpName, pushOp, popOp, rpIndex] of [
        ["b", 0xc5, 0xc1, 0],
        ["d", 0xd5, 0xd1, 2],
        ["h", 0xe5, 0xe1, 4],
    ] as [string, number, number, number][]) {
        const { cpu, memory } = createCPU();
        const results: string[] = [];

        for (let v = 0; v < 0x10000; v += 0x101) {
            cpu.pc = 0;
            cpu.sp = 0x2000;
            cpu.set_rp(rpIndex, v);
            cpu.execute(pushOp);

            cpu.set_rp(rpIndex, 0);
            cpu.execute(popOp);

            results.push(`rp:${hex16(v)} -> rp:${hex16(cpu.rp(rpIndex))}`);
        }
        await writeData(`push_pop_${rpName}`, `PUSH_POP_${rpName.toUpperCase()}`, results);
    }
}

// --- XCHG ---

{
    const { cpu } = createCPU();
    const results: string[] = [];

    for (let de = 0; de < 0x10000; de += 0x1111) {
        for (let hl = 0; hl < 0x10000; hl += 0x1111) {
            cpu.pc = 0;
            cpu.set_rp(2, de);
            cpu.set_rp(4, hl);
            cpu.execute(0xeb); // XCHG
            results.push(`de:${hex16(de)} hl:${hex16(hl)} -> de:${hex16(cpu.de())} hl:${hex16(cpu.hl())}`);
        }
    }
    await writeData("xchg", "XCHG", results);
}

// --- XTHL ---

{
    const { cpu, memory } = createCPU();
    const results: string[] = [];

    for (let hl = 0; hl < 0x10000; hl += 0x1111) {
        for (let stackVal = 0; stackVal < 0x10000; stackVal += 0x1111) {
            cpu.pc = 0;
            cpu.sp = 0x2000;
            cpu.set_rp(4, hl);
            memory.write_raw(0x2000, stackVal & 0xff);
            memory.write_raw(0x2001, (stackVal >> 8) & 0xff);
            cpu.execute(0xe3); // XTHL
            const newStack = memory.read_raw(0x2000) | (memory.read_raw(0x2001) << 8);
            results.push(`hl:${hex16(hl)} stack:${hex16(stackVal)} -> hl:${hex16(cpu.hl())} stack:${hex16(newStack)}`);
        }
    }
    await writeData("xthl", "XTHL", results);
}

// --- SPHL ---

{
    const { cpu } = createCPU();
    const results: string[] = [];

    for (let hl = 0; hl < 0x10000; hl += 0x100) {
        cpu.pc = 0;
        cpu.set_rp(4, hl);
        cpu.execute(0xf9); // SPHL
        results.push(`hl:${hex16(hl)} -> sp:${hex16(cpu.sp)}`);
    }
    await writeData("sphl", "SPHL", results);
}

// --- PCHL ---

{
    const { cpu } = createCPU();
    const results: string[] = [];

    for (let hl = 0; hl < 0x10000; hl += 0x100) {
        cpu.pc = 0;
        cpu.set_rp(4, hl);
        cpu.execute(0xe9); // PCHL
        results.push(`hl:${hex16(hl)} -> pc:${hex16(cpu.pc)}`);
    }
    await writeData("pchl", "PCHL", results);
}

// --- JMP and conditional jumps ---

{
    const { cpu, memory } = createCPU();

    // JMP
    const jmpResults: string[] = [];
    for (let addr = 0; addr < 0x10000; addr += 0x100) {
        cpu.pc = 0;
        memory.write_raw(0, addr & 0xff);
        memory.write_raw(1, (addr >> 8) & 0xff);
        cpu.execute(0xc3); // JMP
        jmpResults.push(`addr:${hex16(addr)} -> pc:${hex16(cpu.pc)}`);
    }
    await writeData("jmp", "JMP", jmpResults);

    // Conditional jumps: JNZ, JZ, JNC, JC, JPO, JPE, JP, JM
    const condJumps = [
        { name: "jnz", opcode: 0xc2, flag: "zf", jumpWhen: 0 },
        { name: "jz", opcode: 0xca, flag: "zf", jumpWhen: 1 },
        { name: "jnc", opcode: 0xd2, flag: "cf", jumpWhen: 0 },
        { name: "jc", opcode: 0xda, flag: "cf", jumpWhen: 1 },
        { name: "jpo", opcode: 0xe2, flag: "pf", jumpWhen: 0 },
        { name: "jpe", opcode: 0xea, flag: "pf", jumpWhen: 1 },
        { name: "jp", opcode: 0xf2, flag: "sf", jumpWhen: 0 },
        { name: "jm", opcode: 0xfa, flag: "sf", jumpWhen: 1 },
    ];

    for (const j of condJumps) {
        const results: string[] = [];
        for (const flagVal of [0, 1]) {
            cpu.pc = 0;
            memory.write_raw(0, 0x00);
            memory.write_raw(1, 0x50); // target = 0x5000
            (cpu as any)[j.flag] = flagVal;
            cpu.execute(j.opcode);
            results.push(`${j.flag}:${flagVal} -> pc:${hex16(cpu.pc)}`);
        }
        await writeData(j.name, j.name.toUpperCase(), results);
    }
}

// --- CALL/RET ---

{
    const { cpu, memory } = createCPU();

    // CALL
    const callResults: string[] = [];
    for (let addr = 0; addr < 0x10000; addr += 0x1000) {
        cpu.pc = 0x100;
        cpu.sp = 0x2000;
        memory.write_raw(0x100, addr & 0xff);
        memory.write_raw(0x101, (addr >> 8) & 0xff);
        cpu.execute(0xcd); // CALL
        const retAddr = memory.read_raw(0x1ffe) | (memory.read_raw(0x1fff) << 8);
        callResults.push(`from:0100 to:${hex16(addr)} -> pc:${hex16(cpu.pc)} sp:${hex16(cpu.sp)} ret:${hex16(retAddr)}`);
    }
    await writeData("call", "CALL", callResults);

    // RET
    const retResults: string[] = [];
    for (let addr = 0; addr < 0x10000; addr += 0x1000) {
        cpu.pc = 0;
        cpu.sp = 0x1ffe;
        memory.write_raw(0x1ffe, addr & 0xff);
        memory.write_raw(0x1fff, (addr >> 8) & 0xff);
        cpu.execute(0xc9); // RET
        retResults.push(`ret_addr:${hex16(addr)} -> pc:${hex16(cpu.pc)} sp:${hex16(cpu.sp)}`);
    }
    await writeData("ret", "RET", retResults);
}

// --- RST ---

{
    const { cpu, memory } = createCPU();
    const results: string[] = [];

    for (let n = 0; n < 8; n++) {
        cpu.pc = 0x100;
        cpu.sp = 0x2000;
        cpu.execute(0xc7 | (n << 3)); // RST n
        results.push(`rst:${n} -> pc:${hex16(cpu.pc)} sp:${hex16(cpu.sp)}`);
    }
    await writeData("rst", "RST", results);
}

// --- EI/DI ---

{
    const { cpu } = createCPU();
    const results: string[] = [];

    for (const start of [0, 1]) {
        cpu.iff = start;
        cpu.pc = 0;
        cpu.execute(0xfb); // EI
        results.push(`ei: iff:${start} -> iff:${cpu.iff}`);
    }
    for (const start of [0, 1]) {
        cpu.iff = start;
        cpu.pc = 0;
        cpu.execute(0xf3); // DI
        results.push(`di: iff:${start} -> iff:${cpu.iff}`);
    }
    await writeData("ei_di", "EI_DI", results);
}

console.log("done");
