import { hex16, hex8 } from "./hex.js";

export interface I8080Instruction {
    cmd: string;
    length: number;
    arg1?: string;
    arg2?: string;
    data1?: boolean;
    data2?: boolean;
    code?: boolean;
    bad?: boolean;
    instr?: string;
}

export function i8080_opcode(opcode: number, byte2: number = 0, byte3: number = 0): I8080Instruction {
    const imm8_ = byte2 & 0xff;
    const imm16_ = imm8_ | ((byte3 & 0xff) << 8);

    const imm8 = hex8(imm8_);
    const imm16 = hex16(imm16_);

    const opcodes: Record<number, I8080Instruction> = {
        0x00: { cmd: "NOP", length: 1 },
        0x01: { cmd: "LXI", length: 3, arg1: "B", arg2: imm16, data2: true },
        0x02: { cmd: "STAX", length: 1, arg1: "B" },
        0x03: { cmd: "INX", length: 1, arg1: "B" },
        0x04: { cmd: "INR", length: 1, arg1: "B" },
        0x05: { cmd: "DCR", length: 1, arg1: "B" },
        0x06: { cmd: "MVI", length: 2, arg1: "B", arg2: imm8 },
        0x07: { cmd: "RLC", length: 1 },
        0x08: { cmd: "NOP?", length: 1, bad: true },
        0x09: { cmd: "DAD", length: 1, arg1: "B" },
        0x0a: { cmd: "LDAX", length: 1, arg1: "B" },
        0x0b: { cmd: "DCX", length: 1, arg1: "B" },
        0x0c: { cmd: "INR", length: 1, arg1: "C" },
        0x0d: { cmd: "DCR", length: 1, arg1: "C" },
        0x0e: { cmd: "MVI", length: 2, arg1: "C", arg2: imm8 },
        0x0f: { cmd: "RRC", length: 1 },
        0x10: { cmd: "NOP?", length: 1, bad: true },
        0x11: { cmd: "LXI", length: 3, arg1: "D", arg2: imm16, data2: true },
        0x12: { cmd: "STAX", length: 1, arg1: "D" },
        0x13: { cmd: "INX", length: 1, arg1: "D" },
        0x14: { cmd: "INR", length: 1, arg1: "D" },
        0x15: { cmd: "DCR", length: 1, arg1: "D" },
        0x16: { cmd: "MVI", length: 2, arg1: "D", arg2: imm8 },
        0x17: { cmd: "RAL", length: 1 },
        0x18: { cmd: "NOP?", length: 1, bad: true },
        0x19: { cmd: "DAD", length: 1, arg1: "D" },
        0x1a: { cmd: "LDAX", length: 1, arg1: "D" },
        0x1b: { cmd: "DCX", length: 1, arg1: "D" },
        0x1c: { cmd: "INR", length: 1, arg1: "E" },
        0x1d: { cmd: "DCR", length: 1, arg1: "E" },
        0x1e: { cmd: "MVI", length: 2, arg1: "E", arg2: imm8 },
        0x1f: { cmd: "RAR", length: 1 },
        0x20: { cmd: "NOP?", length: 1, bad: true },
        0x21: { cmd: "LXI", length: 3, arg1: "H", arg2: imm16, data2: true },
        0x22: { cmd: "SHLD", length: 3, arg1: imm16, data1: true },
        0x23: { cmd: "INX", length: 1, arg1: "H" },
        0x24: { cmd: "INR", length: 1, arg1: "H" },
        0x25: { cmd: "DCR", length: 1, arg1: "H" },
        0x26: { cmd: "MVI", length: 2, arg1: "H", arg2: imm8 },
        0x27: { cmd: "DAA", length: 1 },
        0x28: { cmd: "NOP?", length: 1, bad: true },
        0x29: { cmd: "DAD", length: 1, arg1: "H" },
        0x2a: { cmd: "LHLD", length: 3, arg1: imm16, data1: true },
        0x2b: { cmd: "DCX", length: 1, arg1: "H" },
        0x2c: { cmd: "INR", length: 1, arg1: "L" },
        0x2d: { cmd: "DCR", length: 1, arg1: "L" },
        0x2e: { cmd: "MVI", length: 2, arg1: "L", arg2: imm8 },
        0x2f: { cmd: "CMA", length: 1 },
        0x30: { cmd: "NOP?", length: 1, bad: true },
        0x31: { cmd: "LXI", length: 3, arg1: "SP", arg2: imm16, data2: true },
        0x32: { cmd: "STA", length: 3, arg1: imm16, data1: true },
        0x33: { cmd: "INX", length: 1, arg1: "SP" },
        0x34: { cmd: "INR", length: 1, arg1: "M" },
        0x35: { cmd: "DCR", length: 1, arg1: "M" },
        0x36: { cmd: "MVI", length: 2, arg1: "M", arg2: imm8 },
        0x37: { cmd: "STC", length: 1 },
        0x38: { cmd: "NOP?", length: 1, bad: true },
        0x39: { cmd: "DAD", length: 1, arg1: "SP" },
        0x3a: { cmd: "LDA", length: 3, arg1: imm16, data1: true },
        0x3b: { cmd: "DCX", length: 1, arg1: "SP" },
        0x3c: { cmd: "INR", length: 1, arg1: "A" },
        0x3d: { cmd: "DCR", length: 1, arg1: "A" },
        0x3e: { cmd: "MVI", length: 2, arg1: "A", arg2: imm8 },
        0x3f: { cmd: "CMC", length: 1 },
        0x40: { cmd: "MOV", length: 1, arg1: "B", arg2: "B" },
        0x41: { cmd: "MOV", length: 1, arg1: "B", arg2: "C" },
        0x42: { cmd: "MOV", length: 1, arg1: "B", arg2: "D" },
        0x43: { cmd: "MOV", length: 1, arg1: "B", arg2: "E" },
        0x44: { cmd: "MOV", length: 1, arg1: "B", arg2: "H" },
        0x45: { cmd: "MOV", length: 1, arg1: "B", arg2: "L" },
        0x46: { cmd: "MOV", length: 1, arg1: "B", arg2: "M" },
        0x47: { cmd: "MOV", length: 1, arg1: "B", arg2: "A" },
        0x48: { cmd: "MOV", length: 1, arg1: "C", arg2: "B" },
        0x49: { cmd: "MOV", length: 1, arg1: "C", arg2: "C" },
        0x4a: { cmd: "MOV", length: 1, arg1: "C", arg2: "D" },
        0x4b: { cmd: "MOV", length: 1, arg1: "C", arg2: "E" },
        0x4c: { cmd: "MOV", length: 1, arg1: "C", arg2: "H" },
        0x4d: { cmd: "MOV", length: 1, arg1: "C", arg2: "L" },
        0x4e: { cmd: "MOV", length: 1, arg1: "C", arg2: "M" },
        0x4f: { cmd: "MOV", length: 1, arg1: "C", arg2: "A" },
        0x50: { cmd: "MOV", length: 1, arg1: "D", arg2: "B" },
        0x51: { cmd: "MOV", length: 1, arg1: "D", arg2: "C" },
        0x52: { cmd: "MOV", length: 1, arg1: "D", arg2: "D" },
        0x53: { cmd: "MOV", length: 1, arg1: "D", arg2: "E" },
        0x54: { cmd: "MOV", length: 1, arg1: "D", arg2: "H" },
        0x55: { cmd: "MOV", length: 1, arg1: "D", arg2: "L" },
        0x56: { cmd: "MOV", length: 1, arg1: "D", arg2: "M" },
        0x57: { cmd: "MOV", length: 1, arg1: "D", arg2: "A" },
        0x58: { cmd: "MOV", length: 1, arg1: "E", arg2: "B" },
        0x59: { cmd: "MOV", length: 1, arg1: "E", arg2: "C" },
        0x5a: { cmd: "MOV", length: 1, arg1: "E", arg2: "D" },
        0x5b: { cmd: "MOV", length: 1, arg1: "E", arg2: "E" },
        0x5c: { cmd: "MOV", length: 1, arg1: "E", arg2: "H" },
        0x5d: { cmd: "MOV", length: 1, arg1: "E", arg2: "L" },
        0x5e: { cmd: "MOV", length: 1, arg1: "E", arg2: "M" },
        0x5f: { cmd: "MOV", length: 1, arg1: "E", arg2: "A" },
        0x60: { cmd: "MOV", length: 1, arg1: "H", arg2: "B" },
        0x61: { cmd: "MOV", length: 1, arg1: "H", arg2: "C" },
        0x62: { cmd: "MOV", length: 1, arg1: "H", arg2: "D" },
        0x63: { cmd: "MOV", length: 1, arg1: "H", arg2: "E" },
        0x64: { cmd: "MOV", length: 1, arg1: "H", arg2: "H" },
        0x65: { cmd: "MOV", length: 1, arg1: "H", arg2: "L" },
        0x66: { cmd: "MOV", length: 1, arg1: "H", arg2: "M" },
        0x67: { cmd: "MOV", length: 1, arg1: "H", arg2: "A" },
        0x68: { cmd: "MOV", length: 1, arg1: "L", arg2: "B" },
        0x69: { cmd: "MOV", length: 1, arg1: "L", arg2: "C" },
        0x6a: { cmd: "MOV", length: 1, arg1: "L", arg2: "D" },
        0x6b: { cmd: "MOV", length: 1, arg1: "L", arg2: "E" },
        0x6c: { cmd: "MOV", length: 1, arg1: "L", arg2: "H" },
        0x6d: { cmd: "MOV", length: 1, arg1: "L", arg2: "L" },
        0x6e: { cmd: "MOV", length: 1, arg1: "L", arg2: "M" },
        0x6f: { cmd: "MOV", length: 1, arg1: "L", arg2: "A" },
        0x70: { cmd: "MOV", length: 1, arg1: "M", arg2: "B" },
        0x71: { cmd: "MOV", length: 1, arg1: "M", arg2: "C" },
        0x72: { cmd: "MOV", length: 1, arg1: "M", arg2: "D" },
        0x73: { cmd: "MOV", length: 1, arg1: "M", arg2: "E" },
        0x74: { cmd: "MOV", length: 1, arg1: "M", arg2: "H" },
        0x75: { cmd: "MOV", length: 1, arg1: "M", arg2: "L" },
        0x76: { cmd: "HLT", length: 1 },
        0x77: { cmd: "MOV", length: 1, arg1: "M", arg2: "A" },
        0x78: { cmd: "MOV", length: 1, arg1: "A", arg2: "B" },
        0x79: { cmd: "MOV", length: 1, arg1: "A", arg2: "C" },
        0x7a: { cmd: "MOV", length: 1, arg1: "A", arg2: "D" },
        0x7b: { cmd: "MOV", length: 1, arg1: "A", arg2: "E" },
        0x7c: { cmd: "MOV", length: 1, arg1: "A", arg2: "H" },
        0x7d: { cmd: "MOV", length: 1, arg1: "A", arg2: "L" },
        0x7e: { cmd: "MOV", length: 1, arg1: "A", arg2: "M" },
        0x7f: { cmd: "MOV", length: 1, arg1: "A", arg2: "A" },
        0x80: { cmd: "ADD", length: 1, arg1: "B" },
        0x81: { cmd: "ADD", length: 1, arg1: "C" },
        0x82: { cmd: "ADD", length: 1, arg1: "D" },
        0x83: { cmd: "ADD", length: 1, arg1: "E" },
        0x84: { cmd: "ADD", length: 1, arg1: "H" },
        0x85: { cmd: "ADD", length: 1, arg1: "L" },
        0x86: { cmd: "ADD", length: 1, arg1: "M" },
        0x87: { cmd: "ADD", length: 1, arg1: "A" },
        0x88: { cmd: "ADC", length: 1, arg1: "B" },
        0x89: { cmd: "ADC", length: 1, arg1: "C" },
        0x8a: { cmd: "ADC", length: 1, arg1: "D" },
        0x8b: { cmd: "ADC", length: 1, arg1: "E" },
        0x8c: { cmd: "ADC", length: 1, arg1: "H" },
        0x8d: { cmd: "ADC", length: 1, arg1: "L" },
        0x8e: { cmd: "ADC", length: 1, arg1: "M" },
        0x8f: { cmd: "ADC", length: 1, arg1: "A" },
        0x90: { cmd: "SUB", length: 1, arg1: "B" },
        0x91: { cmd: "SUB", length: 1, arg1: "C" },
        0x92: { cmd: "SUB", length: 1, arg1: "D" },
        0x93: { cmd: "SUB", length: 1, arg1: "E" },
        0x94: { cmd: "SUB", length: 1, arg1: "H" },
        0x95: { cmd: "SUB", length: 1, arg1: "L" },
        0x96: { cmd: "SUB", length: 1, arg1: "M" },
        0x97: { cmd: "SUB", length: 1, arg1: "A" },
        0x98: { cmd: "SBB", length: 1, arg1: "B" },
        0x99: { cmd: "SBB", length: 1, arg1: "C" },
        0x9a: { cmd: "SBB", length: 1, arg1: "D" },
        0x9b: { cmd: "SBB", length: 1, arg1: "E" },
        0x9c: { cmd: "SBB", length: 1, arg1: "H" },
        0x9d: { cmd: "SBB", length: 1, arg1: "L" },
        0x9e: { cmd: "SBB", length: 1, arg1: "M" },
        0x9f: { cmd: "SBB", length: 1, arg1: "A" },
        0xa0: { cmd: "ANA", length: 1, arg1: "B" },
        0xa1: { cmd: "ANA", length: 1, arg1: "C" },
        0xa2: { cmd: "ANA", length: 1, arg1: "D" },
        0xa3: { cmd: "ANA", length: 1, arg1: "E" },
        0xa4: { cmd: "ANA", length: 1, arg1: "H" },
        0xa5: { cmd: "ANA", length: 1, arg1: "L" },
        0xa6: { cmd: "ANA", length: 1, arg1: "M" },
        0xa7: { cmd: "ANA", length: 1, arg1: "A" },
        0xa8: { cmd: "XRA", length: 1, arg1: "B" },
        0xa9: { cmd: "XRA", length: 1, arg1: "C" },
        0xaa: { cmd: "XRA", length: 1, arg1: "D" },
        0xab: { cmd: "XRA", length: 1, arg1: "E" },
        0xac: { cmd: "XRA", length: 1, arg1: "H" },
        0xad: { cmd: "XRA", length: 1, arg1: "L" },
        0xae: { cmd: "XRA", length: 1, arg1: "M" },
        0xaf: { cmd: "XRA", length: 1, arg1: "A" },
        0xb0: { cmd: "ORA", length: 1, arg1: "B" },
        0xb1: { cmd: "ORA", length: 1, arg1: "C" },
        0xb2: { cmd: "ORA", length: 1, arg1: "D" },
        0xb3: { cmd: "ORA", length: 1, arg1: "E" },
        0xb4: { cmd: "ORA", length: 1, arg1: "H" },
        0xb5: { cmd: "ORA", length: 1, arg1: "L" },
        0xb6: { cmd: "ORA", length: 1, arg1: "M" },
        0xb7: { cmd: "ORA", length: 1, arg1: "A" },
        0xb8: { cmd: "CMP", length: 1, arg1: "B" },
        0xb9: { cmd: "CMP", length: 1, arg1: "C" },
        0xba: { cmd: "CMP", length: 1, arg1: "D" },
        0xbb: { cmd: "CMP", length: 1, arg1: "E" },
        0xbc: { cmd: "CMP", length: 1, arg1: "H" },
        0xbd: { cmd: "CMP", length: 1, arg1: "L" },
        0xbe: { cmd: "CMP", length: 1, arg1: "M" },
        0xbf: { cmd: "CMP", length: 1, arg1: "A" },
        0xc0: { cmd: "RNZ", length: 1 },
        0xc1: { cmd: "POP", length: 1, arg1: "B" },
        0xc2: { cmd: "JNZ", length: 3, arg1: imm16, code: true },
        0xc3: { cmd: "JMP", length: 3, arg1: imm16, code: true },
        0xc4: { cmd: "CNZ", length: 3, arg1: imm16, code: true },
        0xc5: { cmd: "PUSH", length: 1, arg1: "B" },
        0xc6: { cmd: "ADI", length: 2, arg1: imm8 },
        0xc7: { cmd: "RST", length: 1, arg1: "0" },
        0xc8: { cmd: "RZ", length: 1 },
        0xc9: { cmd: "RET", length: 1 },
        0xca: { cmd: "JZ", length: 3, arg1: imm16, code: true },
        0xcb: { cmd: "JMP?", length: 3, arg1: imm16, code: true, bad: true },
        0xcc: { cmd: "CZ", length: 3, arg1: imm16, code: true },
        0xcd: { cmd: "CALL", length: 3, arg1: imm16, code: true },
        0xce: { cmd: "ACI", length: 2, arg1: imm8 },
        0xcf: { cmd: "RST", length: 1, arg1: "1" },
        0xd0: { cmd: "RNC", length: 1 },
        0xd1: { cmd: "POP", length: 1, arg1: "D" },
        0xd2: { cmd: "JNC", length: 3, arg1: imm16, code: true },
        0xd3: { cmd: "OUT", length: 2, arg1: imm8 },
        0xd4: { cmd: "CNC", length: 3, arg1: imm16, code: true },
        0xd5: { cmd: "PUSH", length: 1, arg1: "D" },
        0xd6: { cmd: "SUI", length: 2, arg1: imm8 },
        0xd7: { cmd: "RST", length: 1, arg1: "2" },
        0xd8: { cmd: "RC", length: 1 },
        0xd9: { cmd: "RET?", length: 1, bad: true },
        0xda: { cmd: "JC", length: 3, arg1: imm16, code: true },
        0xdb: { cmd: "IN", length: 2, arg1: imm8 },
        0xdc: { cmd: "CC", length: 3, arg1: imm16, code: true },
        0xdd: { cmd: "CALL?", length: 3, arg1: imm16, code: true, bad: true },
        0xde: { cmd: "SBI", length: 2, arg1: imm8 },
        0xdf: { cmd: "RST", length: 1, arg1: "3" },
        0xe0: { cmd: "RPO", length: 1 },
        0xe1: { cmd: "POP", length: 1, arg1: "H" },
        0xe2: { cmd: "JPO", length: 3, arg1: imm16, code: true },
        0xe3: { cmd: "XTHL", length: 1 },
        0xe4: { cmd: "CPO", length: 3, arg1: imm16, code: true },
        0xe5: { cmd: "PUSH", length: 1, arg1: "H" },
        0xe6: { cmd: "ANI", length: 2, arg1: imm8 },
        0xe7: { cmd: "RST", length: 1, arg1: "4" },
        0xe8: { cmd: "RPE", length: 1 },
        0xe9: { cmd: "PCHL", length: 1 },
        0xea: { cmd: "JPE", length: 3, arg1: imm16, code: true },
        0xeb: { cmd: "XCHG", length: 1 },
        0xec: { cmd: "CPE", length: 3, arg1: imm16, code: true },
        0xed: { cmd: "CALL?", length: 3, arg1: imm16, code: true, bad: true },
        0xee: { cmd: "XRI", length: 2, arg1: imm8 },
        0xef: { cmd: "RST", length: 1, arg1: "5" },
        0xf0: { cmd: "RP", length: 1 },
        0xf1: { cmd: "POP", length: 1, arg1: "PSW" },
        0xf2: { cmd: "JP", length: 3, arg1: imm16, code: true },
        0xf3: { cmd: "DI", length: 1 },
        0xf4: { cmd: "CP", length: 3, arg1: imm16, code: true },
        0xf5: { cmd: "PUSH", length: 1, arg1: "PSW" },
        0xf6: { cmd: "ORI", length: 2, arg1: imm8 },
        0xf7: { cmd: "RST", length: 1, arg1: "6" },
        0xf8: { cmd: "RM", length: 1 },
        0xf9: { cmd: "SPHL", length: 1 },
        0xfa: { cmd: "JM", length: 3, arg1: imm16, code: true },
        0xfb: { cmd: "EI", length: 1 },
        0xfd: { cmd: "CALL?", length: 3, arg1: imm16, code: true, bad: true },
        0xfc: { cmd: "CM", length: 3, arg1: imm16, code: true },
        0xfe: { cmd: "CPI", length: 2, arg1: imm8 },
        0xff: { cmd: "RST", length: 1, arg1: "7" },
    };
    const instr = opcodes[opcode];

    const { cmd, arg1, arg2 } = instr;
    instr.instr = cmd.padEnd(5, " ");
    if (arg1) instr.instr += " " + arg1;
    if (arg2) instr.instr += ", " + arg2;
    instr.instr = instr.instr.trim();

    return instr;
}
