default: test build

build: build-core build-tape build-catalog

build-core:
    rm -rf build
    cp -R src build

build-catalog:
    bun tools/build-catalog.js > build/catalog/index.html

build-tape:
    bun tools/build.js tape > build/rk86_tape_catalog.js

release: build release-production

release-production:
    mkdir -p ../docs/classic
    rsync -a build/ ../docs/classic/

serve:
    cd ../docs && python3 -m http.server --bind 127.0.0.1 8000

serve-build:
    cd build && bunx http-server . -p 8000

watch:
    bun tools/watch.ts

test:
    bun test

ci:
    bun install
    bun test

clean:
    rm -rf build node_modules
