// Generates src/lib/catalog_data.ts and src/lib/tape_catalog.ts from static/files + static/catalog
// Source of truth: static/files — every file must have a corresponding static/catalog/<name>/info.md

import { existsSync, readdirSync, readFileSync } from "fs";
import { join } from "path";

const root = join(import.meta.dir, "..");
const filesDir = join(root, "static/files");
const catalogDir = join(root, "static/catalog");
const outCatalogData = join(root, "src/lib/catalog_data.ts");
const outTapeCatalog = join(root, "src/lib/tape_catalog.ts");

const fileNames = readdirSync(filesDir).sort();
const errors: string[] = [];

interface CatalogEntry {
    name: string;
    title: string;
    description: string;
    screenshots: string[];
}

const entries: CatalogEntry[] = [];

for (const name of fileNames) {
    const dir = join(catalogDir, name);
    if (!existsSync(dir)) {
        errors.push(`missing catalog entry: static/catalog/${name}/`);
        continue;
    }

    const infoPath = join(dir, "info.md");
    if (!existsSync(infoPath)) {
        errors.push(`missing info.md: static/catalog/${name}/info.md`);
        continue;
    }

    const lines = readFileSync(infoPath, "utf-8").split("\n");
    const title = lines[0]?.trim() || name;
    const description = lines.slice(1).join("\n").trim();

    const files = readdirSync(dir);
    const screenshots = files.filter((f) => f.endsWith(".png")).sort();

    entries.push({ name, title, description, screenshots });
}

if (errors.length > 0) {
    console.error("catalog build errors:");
    errors.forEach((e) => console.error(`  - ${e}`));
    process.exit(1);
}

// Generate catalog_data.ts
await Bun.write(
    outCatalogData,
    `// auto-generated by build_catalog.ts — do not edit
export interface CatalogEntry {
    name: string;
    title: string;
    description: string;
    screenshots: string[];
}

export const catalog: CatalogEntry[] = ${JSON.stringify(entries, null, 4)};
`,
);

// Generate tape_catalog.ts
await Bun.write(
    outTapeCatalog,
    `// auto-generated by build_catalog.ts — do not edit
export function tape_catalog(): string[] {
    return ${JSON.stringify(fileNames, null, 8)};
}
`,
);

// Generate rk86_version.ts
const now = new Date();
const pad = (n: number) => String(n).padStart(2, "0");
const buildTime = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
await Bun.write(
    join(root, "src/lib/rk86_version.ts"),
    `// auto-generated by build_catalog.ts — do not edit\nexport const version = "${buildTime}";\n`,
);

console.log(`catalog: ${entries.length} entries, ${fileNames.length} files, version: ${buildTime}`);
