// auto-generated by generate_cpu_data.ts
export const RST: string[] = [
    "rst:0 -> pc:0000 sp:1FFE",
    "rst:1 -> pc:0008 sp:1FFE",
    "rst:2 -> pc:0010 sp:1FFE",
    "rst:3 -> pc:0018 sp:1FFE",
    "rst:4 -> pc:0020 sp:1FFE",
    "rst:5 -> pc:0028 sp:1FFE",
    "rst:6 -> pc:0030 sp:1FFE",
    "rst:7 -> pc:0038 sp:1FFE",
];
