// Generates src/lib/component/embedded_monitors.ts with base64-encoded monitor ROMs.
// Lets the <radio86-emulator> npm package boot without fetching ROM files from the host.

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const root = join(import.meta.dir, "..");
const filesDir = join(root, "static/files");
const out = join(root, "src/lib/component/embedded_monitors.ts");

const monitors = ["mon32.bin", "mon32-color.bin"];

const entries = monitors.map((name) => {
    const bytes = readFileSync(join(filesDir, name));
    return `    "${name}": "${bytes.toString("base64")}",`;
});

const banner = "// AUTO-GENERATED by tools/build_embedded_monitors.ts — do not edit.";
const body = `${banner}\n\nexport const EMBEDDED_MONITORS: Record<string, string> = {\n${entries.join("\n")}\n};\n`;

writeFileSync(out, body);
console.log(`embedded monitors → ${out} (${monitors.join(", ")})`);
