// Generates src/lib/catalog_data.ts and src/lib/tape_catalog.ts from static/files + static/catalog
// Source of truth: static/files — every file must have a corresponding static/catalog/<name>/info.md

import { existsSync, readdirSync, readFileSync } from "fs";
import { join } from "path";

const root = join(import.meta.dir, "..");
const filesDir = join(root, "static/files");
const catalogDir = join(root, "static/catalog");
const outCatalogData = join(root, "src/lib/catalog_data.ts");
const outTapeCatalog = join(root, "src/lib/tape_catalog.ts");

const fileNames = readdirSync(filesDir).sort();
const errors: string[] = [];

interface CatalogEntry {
    name: string;
    title: string;
    description: string;
    screenshots: string[];
    start: number;
    end: number;
    size: number;
    entry: number;
    checkSum: number;
    leadingE6: boolean;
}

function rk86_check_sum(v: Uint8Array): number {
    let sum = 0;
    let j = 0;
    while (j < v.length - 1) {
        const c = v[j];
        sum = (sum + c + (c << 8)) & 0xffff;
        j += 1;
    }
    const sum_h = sum & 0xff00;
    const sum_l = sum & 0xff;
    sum = sum_h | ((sum_l + v[j]) & 0xff);
    return sum;
}

const skip_check_sum = new Set(["I8080TST.GAM", "OilsWell.rkr"]);

function extract_metadata(name: string, image: Uint8Array) {
    if (name.endsWith(".json")) {
        // Emulator snapshot (info/SNAPSHOT.md) — metadata comes from the
        // JSON itself, the entry point is the restored PC.
        const json = JSON.parse(new TextDecoder().decode(image));
        const start = parseInt(json.start) || 0;
        const end = parseInt(json.end) || 0xffff;
        return {
            start,
            end,
            size: end - start + 1,
            entry: parseInt(json.cpu?.pc) || 0,
            checkSum: rk86_check_sum(image),
            leadingE6: false,
        };
    }

    if (name.endsWith(".bin")) {
        let start = 0;
        let entry = 0;
        if (name.startsWith("mon_")) {
            start = 0x10000 - image.length;
            entry = 0xf800;
        }
        return {
            start,
            end: start + image.length - 1,
            size: image.length,
            entry,
            checkSum: rk86_check_sum(image),
            leadingE6: false,
        };
    }

    const w = (i: number) => ((image[i] & 0xff) << 8) | (image[i + 1] & 0xff);
    let i = 0;
    const leadingE6 = image[i] === 0xe6;
    if (leadingE6) i += 1;
    const start = w(i);
    const end = w(i + 2);
    const size = end - start + 1;
    i += 4;

    const realCheckSum = rk86_check_sum(image.slice(i, i + size));
    i += size;

    while (i < image.length && image[i] !== 0xe6) i += 1;
    const trailerCheckSum = i + 2 < image.length ? w(i + 1) : realCheckSum;

    if (trailerCheckSum !== realCheckSum && !skip_check_sum.has(name)) {
        errors.push(
            `${name}: trailer checksum 0x${trailerCheckSum.toString(16).padStart(4, "0").toUpperCase()} != computed 0x${realCheckSum.toString(16).padStart(4, "0").toUpperCase()}`,
        );
    }

    let entry = start;
    if (name === "PVO.GAM") entry = 0x3400;
    if (name === "RAMDOS.PKI") entry = 0x3600;

    return { start, end, size, entry, checkSum: realCheckSum, leadingE6 };
}

const entries: CatalogEntry[] = [];

for (const name of fileNames) {
    const dir = join(catalogDir, name);
    if (!existsSync(dir)) {
        errors.push(`missing catalog entry: static/catalog/${name}/`);
        continue;
    }

    const infoPath = join(dir, "info.md");
    if (!existsSync(infoPath)) {
        errors.push(`missing info.md: static/catalog/${name}/info.md`);
        continue;
    }

    const lines = readFileSync(infoPath, "utf-8").split("\n");
    const title = lines[0]?.trim() || name;
    const description = lines.slice(1).join("\n").trim();

    const files = readdirSync(dir);
    const screenshots = files.filter((f) => f.endsWith(".png")).sort();

    const image = new Uint8Array(readFileSync(join(filesDir, name)));
    const meta = extract_metadata(name, image);

    entries.push({ name, title, description, screenshots, ...meta });
}

if (errors.length > 0) {
    console.error("catalog build errors:");
    errors.forEach((e) => console.error(`  - ${e}`));
    process.exit(1);
}

// Generate catalog_data.ts
await Bun.write(
    outCatalogData,
    `// auto-generated by build_catalog.ts — do not edit
export interface CatalogEntry {
    name: string;
    title: string;
    description: string;
    screenshots: string[];
    start: number;
    end: number;
    size: number;
    entry: number;
    checkSum: number;
    leadingE6: boolean;
}

export const catalog: CatalogEntry[] = ${JSON.stringify(entries, null, 4)};
`,
);

// Generate tape_catalog.ts
await Bun.write(
    outTapeCatalog,
    `// auto-generated by build_catalog.ts — do not edit
export function tape_catalog(): string[] {
    return ${JSON.stringify(fileNames, null, 8)};
}
`,
);

// Generate rk86_version.ts
const now = new Date();
const pad = (n: number) => String(n).padStart(2, "0");
const buildTime = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
await Bun.write(
    join(root, "src/lib/rk86_version.ts"),
    `// auto-generated by build_catalog.ts — do not edit\nexport const version = "${buildTime}";\n`,
);

console.log(`catalog: ${entries.length} entries, ${fileNames.length} files, version: ${buildTime}`);
